// @ts-check
import { defineConfig } from 'astro/config';

import { SITE_URL } from './src/lib/site.ts';

// The site is fully static: no adapter, no server runtime, no backend.
// Cloudflare Pages serves the `dist/` output directly.
//
// The sitemap is generated by `src/pages/sitemap.xml.ts` rather than by an
// integration — it is a dozen lines against the same product data the pages
// use, which is cheaper than carrying a dependency for it.
export default defineConfig({
  site: SITE_URL,
  build: {
    // Emit `/about/index.html` so URLs stay clean without host-side rewrites.
    format: 'directory',
  },
  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'hover',
  },
});
