// @ts-check
import { defineConfig } from 'astro/config';

import { SITE_URL } from './src/lib/site.ts';

// The site is fully static: no adapter, no server runtime, no backend.
// GitHub Actions builds `dist/` and GitHub Pages serves it directly at the
// apex domain in `public/CNAME`. Because the site lives at the root of a
// custom domain rather than under `/<repository>/`, there is deliberately no
// `base` — adding one would break every root-relative asset and link.
//
// The sitemap is generated by `src/pages/sitemap.xml.ts` rather than by an
// integration — it is a dozen lines against the same product data the pages
// use, which is cheaper than carrying a dependency for it.
export default defineConfig({
  site: SITE_URL,
  build: {
    // Emit `/about/index.html` so URLs stay clean without host-side rewrites.
    format: 'directory',
  },
  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'hover',
  },
});
